#spring.application.name=demo
#server.port=8081
##k?t n?i MySQL
#spring.datasource.url=jdbc:mysql://localhost:3306/clinic_management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#spring.datasource.username=root
##spring.datasource.password=123123123
#spring.datasource.password=Orenda123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


spring.application.name=demo
server.port=8081
#k?t n?i MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/clinic_management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Orenda123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect